import { Language } from './types';

export const ADMIN_PASS = 'admin123';

export const LANGUAGE_CONFIG: Record<Language, { label: string; flag: string }> = {
  PL:  { label: 'PL', flag: '🇵🇱' },
  ENG: { label: 'EN', flag: '🇬🇧' },
  UKR: { label: 'UA', flag: '🇺🇦' },
};

const PL = {
  title: 'PESEL Master',
  subtitle: 'Generator Tożsamości i Weryfikacja',
  manualEntry: 'Nowy Wniosek',
  firstName: 'Imię',
  lastName: 'Nazwisko',
  dob: 'Data Urodzenia',
  gender: 'Płeć',
  nationality: 'Obywatelstwo',
  male: 'Mężczyzna',
  female: 'Kobieta',
  generateIdentity: 'Generuj Tożsamość',
  activeIdentity: 'Twoja Tożsamość',
  verification: 'Weryfikacja',
  readOutLoud: 'Czytaj na głos',
  dictate: 'Dyktuj',
  explainStructure: 'Struktura PESEL',
  a11yOptions: 'Dostępność',
  textSize: 'Rozmiar Tekstu',
  highContrast: 'Wysoki Kontrast',
  highContrastDesc: 'Ostrzejsze kolory',
  applyChanges: 'Zastosuj',
  searchPrompt:
    'Wypełnij formularz, aby wygenerować PESEL. Wymagane: ID/Paszport, potwierdzenie zameldowania (>6 m-cy) oraz opłata 17 PLN.',
  footerStandard: 'Standard 1-3-7-9',
  footerAi: 'System Weryfikacji',
  footerDesc:
    'Generator jest zgodny ze standardem PESEL. Dane są przetwarzane lokalnie w celu bezpiecznej weryfikacji dokumentów.',
  verify: 'Wgraj i Sprawdź Dokumenty',
  docVerification: 'Weryfikacja Tożsamości',
  idDesc: 'Wgraj dowód, paszport lub potwierdzenie zameldowania (>6 m-cy).',
  statusPending: 'W trakcie weryfikacji',
  statusVerified: 'Zweryfikowany',
  statusRejected: 'Odrzucony',
  aiChecking: 'Przesyłanie dokumentów...',
  adminLogin: 'Panel Administratora',
  password: 'Hasło',
  login: 'Zaloguj',
  adminPanel: 'Baza Danych (Admin)',
  backToUser: 'Powrót do Generatora',
  exportDb: 'Eksportuj (.json)',
  totalRecords: 'Wszystkich rekordów',
  invalidPass: 'Błędne hasło',
  feeNotice: 'Opłata skarbowa: 17 PLN',
  payToVerify: 'Opłać wniosek (17 PLN)',
  paymentMethod: 'Wybierz metodę płatności',
  unpaid: 'Nieopłacony',
  paid: 'Opłacony',
  listening: 'Słucham...',
  // Payment simulation
  payNow: 'Zapłać 17 PLN',
  selectMethod: 'Wybierz metodę i kliknij Dalej',
  payCardNumber: 'Numer karty',
  payCardName: 'Imię właściciela karty',
  payCardExpiry: 'Data ważności',
  payCardCvv: 'CVV',
  blikCode: 'Kod BLIK',
  blikEnter: 'Wpisz 6-cyfrowy kod BLIK z aplikacji bankowej',
  paymentConnecting: 'Łączenie z bankiem...',
  paymentAuthorizing: 'Autoryzacja płatności...',
  paymentFinalizing: 'Finalizowanie transakcji...',
  processingPayment: 'Przetwarzanie płatności...',
  paymentSuccess: 'Płatność zaakceptowana',
  paymentConfirmed: 'Płatność 17 PLN potwierdzona',
  transactionId: 'ID Transakcji',
  amount: 'Kwota',
  method: 'Metoda',
  time: 'Godzina',
  continueBtn: 'Kontynuuj →',
  dontClose: 'Nie zamykaj tego okna',
  authWith: 'Autoryzuj przez',
  authenticateBtn: 'Autoryzuj i zapłać',
  // Under review
  underReview: 'Wniosek złożony — w trakcie weryfikacji',
  underReviewDesc:
    'Twój wniosek o numer PESEL jest przetwarzany. Zostaniesz poinformowany, gdy weryfikacja dobiegnie końca.',
  newApplication: 'Nowy Wniosek',
  applicationRef: 'Nr wniosku',
  submittedAt: 'Złożono',
  // Human review
  reviewPanel: 'Weryfikacja Dokumentów',
  reviewDocuments: 'Weryfikacja Dokumentów',
  reviewQueue: 'W kolejce',
  noPendingDocs: 'Brak dokumentów do weryfikacji',
  viewDocument: 'Zobacz dokument',
  approve: 'Zatwierdź',
  reject: 'Odrzuć',
  backToAdmin: 'Powrót do Panelu',
  // Wnioskodawca (applicant) section
  applicantSection: 'Wnioskodawca',
  applicantSectionDesc: 'Osoba składająca wniosek i adres do korespondencji.',
  personSection: 'Osoba, której dotyczy wniosek',
  applicantFirstName: 'Imię wnioskodawcy',
  applicantLastName: 'Nazwisko wnioskodawcy',
  street: 'Ulica',
  houseNumber: 'Numer domu',
  apartmentNumber: 'Numer lokalu',
  postalCode: 'Kod pocztowy',
  city: 'Miejscowość',

  // Wizard steps
  step: 'Krok',
  of: 'z',
  previous: 'Wstecz',
  next: 'Dalej',

  // Person additional info (Step 2)
  secondName: 'Imię drugie',
  otherNames: 'Imiona kolejne',
  maidenName: 'Nazwisko rodowe',
  birthPlace: 'Miejsce urodzenia',
  countryOfBirth: 'Kraj urodzenia',
  countryOfResidence: 'Kraj zamieszkania',
  citizenshipStatus: 'Obywatelstwo/Status',
  citizenshipPolish: 'Polskie',
  citizenshipStateless: 'Bezpaństwowiec',
  citizenshipOther: 'Inne',

  // Family info
  familySection: 'Dane rodziców',
  fatherFirstName: "Imię ojca",
  fatherMaidenName: "Nazwisko rodowe ojca",
  motherFirstName: "Imię matki",
  motherMaidenName: "Nazwisko rodowe matki",
  civRegistryOffice: 'Urząd stanu cywilnego (urodzenia)',

  // Document info
  documentSection: 'Dokumenty',
  idSection: 'Dowód osobisty',
  idSeriesNumber: 'Seria i numer',
  idValidityDate: 'Data ważności',
  idIssuingAuthority: 'Organ wydający',
  passportSection: 'Paszport',
  passportSeriesNumber: 'Seria i numer',
  passportValidityDate: 'Data ważności',
  otherDocSection: 'Inny dokument',
  otherDocSeriesNumber: 'Seria i numer',
  otherDocValidityDate: 'Data ważności',

  // Marital status
  maritalStatusSection: 'Stan cywilny',
  maritalStatus: 'Stan cywilny',
  maritalSingle: 'Kawaler/Panna',
  maritalMarried: 'Żonaty/Zamężna',
  maritalDivorced: 'Rozwiedziony/Rozwiedziona',
  maritalWidow: 'Wdowiec/Wdowa',
  spouseFirstName: 'Imię małżonka',
  spouseMaidenName: 'Nazwisko rodowe małżonka',
  spousePesel: 'PESEL małżonka',

  // Notification
  notificationSection: 'Powiadomienie o nadaniu PESEL',
  notificationMethod: 'Forma dokumentu',
  notificationPaper: 'Papierowa',
  notificationElectronic: 'Elektroniczna',
  emailAddress: 'Adres e-mail',
  epuapAddress: 'Adres skrzynki ePUAP',

  // Form hints
  optional: '(opcjonalnie)',
  required: '(wymagane)',
  fillIfAvailable: 'Wypełnij, jeśli dane są dostępne',
} as const;

const ENG = {
  title: 'PESEL Master',
  subtitle: 'Identity Generator & Verification',
  manualEntry: 'New Application',
  firstName: 'First Name',
  lastName: 'Last Name',
  dob: 'Birth Date',
  gender: 'Gender',
  nationality: 'Nationality',
  male: 'Male',
  female: 'Female',
  generateIdentity: 'Generate Identity',
  activeIdentity: 'Your Identity',
  verification: 'Verification',
  readOutLoud: 'Read aloud',
  dictate: 'Dictate',
  explainStructure: 'PESEL Structure',
  a11yOptions: 'Accessibility',
  textSize: 'Text Size',
  highContrast: 'High Contrast',
  highContrastDesc: 'Sharper colors',
  applyChanges: 'Apply',
  searchPrompt:
    'Fill the form to generate a PESEL. Required: ID/Passport, proof of residence (>6 months), and a 17 PLN fee.',
  footerStandard: '1-3-7-9 Standard',
  footerAi: 'Validation System',
  footerDesc:
    'Generator follows the PESEL standard. Data is processed locally for secure document verification.',
  verify: 'Upload & Verify Docs',
  docVerification: 'Identity Verification',
  idDesc: 'Upload ID, passport, or proof of residence (>6 months).',
  statusPending: 'Under Review',
  statusVerified: 'Verified',
  statusRejected: 'Rejected',
  aiChecking: 'Uploading documents...',
  adminLogin: 'Admin Panel',
  password: 'Password',
  login: 'Login',
  adminPanel: 'Hidden Database (Admin)',
  backToUser: 'Back to Generator',
  exportDb: 'Export (.json)',
  totalRecords: 'Total Records',
  invalidPass: 'Invalid password',
  feeNotice: 'Service Fee: 17 PLN',
  payToVerify: 'Pay Application Fee (17 PLN)',
  paymentMethod: 'Select Payment Method',
  unpaid: 'Unpaid',
  paid: 'Paid',
  listening: 'Listening...',
  payNow: 'Pay 17 PLN',
  selectMethod: 'Select a method and click Continue',
  payCardNumber: 'Card Number',
  payCardName: 'Cardholder Name',
  payCardExpiry: 'Expiry Date',
  payCardCvv: 'CVV',
  blikCode: 'BLIK Code',
  blikEnter: 'Enter the 6-digit BLIK code from your banking app',
  paymentConnecting: 'Connecting to bank...',
  paymentAuthorizing: 'Authorizing payment...',
  paymentFinalizing: 'Finalizing transaction...',
  processingPayment: 'Processing payment...',
  paymentSuccess: 'Payment successful',
  paymentConfirmed: 'Payment of 17 PLN confirmed',
  transactionId: 'Transaction ID',
  amount: 'Amount',
  method: 'Method',
  time: 'Time',
  continueBtn: 'Continue →',
  dontClose: 'Do not close this window',
  authWith: 'Authorize with',
  authenticateBtn: 'Authenticate & Pay',
  underReview: 'Application submitted — under review',
  underReviewDesc:
    'Your PESEL application is being processed. You will be notified once verification is complete.',
  newApplication: 'New Application',
  applicationRef: 'Reference',
  submittedAt: 'Submitted',
  // Human review
  reviewPanel: 'Document Review',
  reviewDocuments: 'Document Review',
  reviewQueue: 'In queue',
  noPendingDocs: 'No documents pending review',
  viewDocument: 'View document',
  approve: 'Approve',
  reject: 'Reject',
  backToAdmin: 'Back to Admin',
  // Wnioskodawca (applicant) section
  applicantSection: 'Applicant',
  applicantSectionDesc: 'The person submitting this application and their correspondence address.',
  personSection: 'Person the application concerns',
  applicantFirstName: "Applicant's First Name",
  applicantLastName: "Applicant's Last Name",
  street: 'Street',
  houseNumber: 'House No.',
  apartmentNumber: 'Apartment No.',
  postalCode: 'Postal Code',
  city: 'City',

  // Wizard steps
  step: 'Step',
  of: 'of',
  previous: 'Previous',
  next: 'Next',

  // Person additional info (Step 2)
  secondName: 'Second Name',
  otherNames: 'Other Names',
  maidenName: 'Maiden Name',
  birthPlace: 'Place of Birth',
  countryOfBirth: 'Country of Birth',
  countryOfResidence: 'Country of Residence',
  citizenshipStatus: 'Citizenship/Status',
  citizenshipPolish: 'Polish',
  citizenshipStateless: 'Stateless',
  citizenshipOther: 'Other',

  // Family info
  familySection: 'Parent Information',
  fatherFirstName: 'Father\'s First Name',
  fatherMaidenName: 'Father\'s Maiden Name',
  motherFirstName: 'Mother\'s First Name',
  motherMaidenName: 'Mother\'s Maiden Name',
  civRegistryOffice: 'Civil Registry Office (Birth)',

  // Document info
  documentSection: 'Documents',
  idSection: 'ID Card',
  idSeriesNumber: 'Series and Number',
  idValidityDate: 'Validity Date',
  idIssuingAuthority: 'Issuing Authority',
  passportSection: 'Passport',
  passportSeriesNumber: 'Series and Number',
  passportValidityDate: 'Validity Date',
  otherDocSection: 'Other Document',
  otherDocSeriesNumber: 'Series and Number',
  otherDocValidityDate: 'Validity Date',

  // Marital status
  maritalStatusSection: 'Marital Status',
  maritalStatus: 'Marital Status',
  maritalSingle: 'Single',
  maritalMarried: 'Married',
  maritalDivorced: 'Divorced',
  maritalWidow: 'Widow/Widower',
  spouseFirstName: 'Spouse\'s First Name',
  spouseMaidenName: 'Spouse\'s Maiden Name',
  spousePesel: 'Spouse\'s PESEL',

  // Notification
  notificationSection: 'PESEL Assignment Notification',
  notificationMethod: 'Document Form',
  notificationPaper: 'Paper',
  notificationElectronic: 'Electronic',
  emailAddress: 'Email Address',
  epuapAddress: 'ePUAP Address',

  // Form hints
  optional: '(optional)',
  required: '(required)',
  fillIfAvailable: 'Fill if data is available',
} as const;

const UKR = {
  title: 'PESEL Майстер',
  subtitle: 'Генератор ідентифікації та перевірка',
  manualEntry: 'Нова заявка',
  firstName: "Ім'я",
  lastName: 'Прізвище',
  dob: 'Дата народження',
  gender: 'Стать',
  nationality: 'Громадянство',
  male: 'Чоловік',
  female: 'Жінка',
  generateIdentity: 'Створити особу',
  activeIdentity: 'Ваша особа',
  verification: 'Перевірка',
  readOutLoud: 'Читати вголос',
  dictate: 'Диктувати',
  explainStructure: 'Структура PESEL',
  a11yOptions: 'Доступність',
  textSize: 'Розмір тексту',
  highContrast: 'Високий контраст',
  highContrastDesc: 'Чіткіші кольори',
  applyChanges: 'Застосувати',
  searchPrompt:
    'Заповніть форму, щоб згенерувати PESEL. Необхідно: ID/Паспорт, підтвердження проживання (>6 міс) та збір 17 PLN.',
  footerStandard: 'Стандарт 1-3-7-9',
  footerAi: 'Система верифікації',
  footerDesc:
    'Генератор відповідає стандарту PESEL. Дані обробляються локально для автоматичної перевірки документів.',
  verify: 'Завантажити та перевірити',
  docVerification: 'Перевірка особи',
  idDesc: 'Завантажте ID, паспорт або підтвердження проживання (>6 міс).',
  statusPending: 'На перевірці',
  statusVerified: 'Підтверджено',
  statusRejected: 'Відхилено',
  aiChecking: 'Завантаження документів...',
  adminLogin: 'Панель адміністратора',
  password: 'Пароль',
  login: 'Увійти',
  adminPanel: 'Прихована база (Admin)',
  backToUser: 'Назад до генератора',
  exportDb: 'Експорт (.json)',
  totalRecords: 'Всього записів',
  invalidPass: 'Невірний пароль',
  feeNotice: 'Збір: 17 PLN',
  payToVerify: 'Сплатити збір (17 PLN)',
  paymentMethod: 'Оберіть метод оплати',
  unpaid: 'Неоплачено',
  paid: 'Оплачено',
  listening: 'Слухаю...',
  payNow: 'Сплатити 17 PLN',
  selectMethod: 'Оберіть метод і натисніть Далі',
  payCardNumber: 'Номер картки',
  payCardName: "Ім'я власника картки",
  payCardExpiry: 'Термін дії',
  payCardCvv: 'CVV',
  blikCode: 'Код BLIK',
  blikEnter: 'Введіть 6-значний код BLIK з банківського додатку',
  paymentConnecting: 'Підключення до банку...',
  paymentAuthorizing: 'Авторизація платежу...',
  paymentFinalizing: 'Завершення транзакції...',
  processingPayment: 'Обробка платежу...',
  paymentSuccess: 'Оплата прийнята',
  paymentConfirmed: 'Платіж 17 PLN підтверджено',
  transactionId: 'ID транзакції',
  amount: 'Сума',
  method: 'Метод',
  time: 'Час',
  continueBtn: 'Продовжити →',
  dontClose: 'Не закривайте це вікно',
  authWith: 'Авторизуватися через',
  authenticateBtn: 'Авторизуватися та сплатити',
  underReview: 'Заявку подано — на перевірці',
  underReviewDesc:
    'Вашу заявку на номер PESEL обробляється. Ви отримаєте повідомлення після завершення верифікації.',
  newApplication: 'Нова заявка',
  applicationRef: 'Номер заявки',
  submittedAt: 'Подано',
  // Human review
  reviewPanel: 'Перевірка документів',
  reviewDocuments: 'Перевірка документів',
  reviewQueue: 'В черзі',
  noPendingDocs: 'Немає документів на перевірці',
  viewDocument: 'Переглянути документ',
  approve: 'Підтвердити',
  reject: 'Відхилити',
  backToAdmin: 'Назад до панелі',
  // Wnioskodawca (applicant) section
  applicantSection: 'Заявник',
  applicantSectionDesc: 'Особа, яка подає цю заявку, та її адреса для листування.',
  personSection: 'Особа, стосовно якої подається заявка',
  applicantFirstName: "Ім'я заявника",
  applicantLastName: 'Прізвище заявника',
  street: 'Вулиця',
  houseNumber: 'Номер будинку',
  apartmentNumber: 'Номер квартири',
  postalCode: 'Поштовий індекс',
  city: 'Місто',

  // Wizard steps
  step: 'Крок',
  of: 'з',
  previous: 'Назад',
  next: 'Далі',

  // Person additional info (Step 2)
  secondName: 'Друге ім\'я',
  otherNames: 'Інші імена',
  maidenName: 'Дівоче прізвище',
  birthPlace: 'Місце народження',
  countryOfBirth: 'Країна народження',
  countryOfResidence: 'Країна проживання',
  citizenshipStatus: 'Громадянство/Статус',
  citizenshipPolish: 'Польське',
  citizenshipStateless: 'Без громадянства',
  citizenshipOther: 'Інше',

  // Family info
  familySection: 'Інформація про батьків',
  fatherFirstName: "Ім'я батька",
  fatherMaidenName: 'Дівоче прізвище батька',
  motherFirstName: "Ім'я матері",
  motherMaidenName: 'Дівоче прізвище матері',
  civRegistryOffice: 'Орган реєстрації (Народження)',

  // Document info
  documentSection: 'Документи',
  idSection: 'Посвідчення особи',
  idSeriesNumber: 'Серія та номер',
  idValidityDate: 'Дата закінчення дії',
  idIssuingAuthority: 'Орган видачі',
  passportSection: 'Паспорт',
  passportSeriesNumber: 'Серія та номер',
  passportValidityDate: 'Дата закінчення дії',
  otherDocSection: 'Інший документ',
  otherDocSeriesNumber: 'Серія та номер',
  otherDocValidityDate: 'Дата закінчення дії',

  // Marital status
  maritalStatusSection: 'Сімейний стан',
  maritalStatus: 'Сімейний стан',
  maritalSingle: 'Холостяк/Не заміжня',
  maritalMarried: 'Одружений/Заміжня',
  maritalDivorced: 'Розлучений/Розлучена',
  maritalWidow: 'Вдівець/Вдова',
  spouseFirstName: "Ім'я супутника",
  spouseMaidenName: 'Дівоче прізвище супутника',
  spousePesel: 'PESEL супутника',

  // Notification
  notificationSection: 'Повідомлення про присвоєння PESEL',
  notificationMethod: 'Форма документа',
  notificationPaper: 'Папір',
  notificationElectronic: 'Електроний',
  emailAddress: 'Адреса електронної пошти',
  epuapAddress: 'Адреса скриньки ePUAP',

  // Form hints
  optional: '(опціонально)',
  required: '(обов\'язково)',
  fillIfAvailable: 'Заповніть, якщо доступні дані',
} as const;

export const TRANSLATIONS = { PL, ENG, UKR };

/** Union of all translation key names — use this as the type for `t` prop. */
export type TranslationKey = keyof typeof PL;